'use strict';
const $=id=>document.getElementById(id),canvas=$('plot'),ctx=canvas.getContext('2d');
const reference=[[0,0],[1,0],[0,1],[-1,0],[0,-1]];
let info=null,result=null,zoom=2,pan=[0,0],drag=null,width=1,height=1,sampleVersion=0,jobVersion=0,jobId=null;
let draftRoots=reference.map(p=>[...p]),rootDrag=null;
function rotate(p){const y=+$('yaw').value*Math.PI/180,t=+$('pitch').value*Math.PI/180,c=Math.cos(y),s=Math.sin(y),a=c*p[0]-s*p[1],b=s*p[0]+c*p[1];return [Math.cos(t)*a-Math.sin(t)*p[2],b,Math.sin(t)*a+Math.cos(t)*p[2]];}
function draw(){const box=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;width=box.width;height=box.height;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#fffef9';ctx.fillRect(0,0,width,height);
 const sphere=$('view').value==='sphere',radius=Math.min(width,height)*.43,cx=width/2,cy=height/2;let visible=0;
 if(sphere){visible=SphereView.draw(ctx,result?.points||[],rotate,width,height,+$('size').value);}
 else{ctx.strokeStyle='#dce4d7';ctx.beginPath();ctx.moveTo(0,cy+pan[1]*radius/zoom);ctx.lineTo(width,cy+pan[1]*radius/zoom);ctx.moveTo(cx-pan[0]*radius/zoom,0);ctx.lineTo(cx-pan[0]*radius/zoom,height);ctx.stroke();ctx.fillStyle='rgba(19,103,104,.65)';const size=+$('size').value,axis=+$('view').value,other=[0,1,2].filter(i=>i!==axis);
 for(const source of result?.points||[]){const p=rotate(source);if(Math.abs(p[axis])<1e-10)continue;const x=(p[other[0]]/p[axis]-pan[0])/zoom,y=(p[other[1]]/p[axis]-pan[1])/zoom,px=cx+radius*x,py=cy-radius*y;if(px<0||px>width||py<0||py>height)continue;ctx.fillRect(px-size/2,py-size/2,size,size);visible++;}}
 $('counter').textContent=result?(sphere?`${visible.toLocaleString()} antipodal lifts`:`${visible.toLocaleString()} / ${result.points.length.toLocaleString()} visible`):'No points yet';$('plotTitle').textContent=sphere?'Sphere S² · lifted limit map':`Affine chart · X${$('view').value} ≠ 0`;
 $('viewNote').textContent=sphere?'Both antipodal lifts are shown. Teal: front hemisphere; violet: rear hemisphere. Drag to rotate.':'Points can leave this chart through infinity. Switch charts or rotate to inspect them.';
}
async function api(url,payload){const response=await fetch(url,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
function format(z){return `${z[0]}${z[1]<0?' − ':' + '}${Math.abs(z[1])}i`;}
async function loadInfo(fill=false){const next=await api('api/info');if(info&&info.id!==next.id){sampleVersion++;result=null;$('json').disabled=$('png').disabled=true;}info=next;
 $('representation').textContent=`${info.surface}\n${info.spin}\nA = ${format(info.settings.A)}; B = ${format(info.settings.B)}`;$('representation').style.whiteSpace='pre-line';$('activeTag').textContent=`Active · level ${info.settings.level}`;
 $('accuracy').textContent=`Surface-relation error: ${info.relation_error.toExponential(2)} (Frobenius norm). ${info.relation_error>.01?'This is a coarse holonomy approximation; increase resolution before interpreting fine detail. ':''}More sampled points do not improve the underlying holonomy accuracy.`;
 if(!$('spin').options.length){for(const spin of info.spins){const option=document.createElement('option');option.value=spin.id;option.textContent=spin.label;$('spin').append(option);}}
 if(fill)fillSettings(info.settings);draw();return next;
}
async function generate(){if(!info)return;const version=++sampleVersion,id=info.id;$('sample').disabled=true;$('status').textContent='Sampling group elements…';try{const data=await api('api/sample',{representation_id:id,mode:$('mode').value,count:+$('count').value,length:+$('length').value,seed:+$('seed').value});if(version!==sampleVersion||id!==info.id)return;result=data;const d=data.diagnostics;$('status').textContent=`${d.unique.toLocaleString()} projective points · ${d.seconds.toFixed(2)} s`;$('stats').textContent=`${d.seed_eigenlines} seed eigenlines · ${d.rejected} unresolved candidates · word-length bound ${d.maximum_represented_word_length}`;$('json').disabled=$('png').disabled=false;draw();}catch(e){if(version===sampleVersion)$('status').textContent=e.message;}finally{if(version===sampleVersion)$('sample').disabled=false;}}
function changed(){if(!jobId)$('computeStatus').textContent='Parameters edited; click Recompute to apply.';$('computeStatus').classList.add('dirty');updateBasis();}
function rootControls(){const host=$('rootFields');host.replaceChildren();for(let i=2;i<5;i++){const row=document.createElement('div');row.className='root-row';const label=document.createElement('span');label.textContent=`a${i}`;row.append(label);for(let j=0;j<2;j++){const input=document.createElement('input');input.type='number';input.step='.001';input.min=reference[i][j]-.18;input.max=reference[i][j]+.18;input.value=draftRoots[i][j];input.id=`root${i}_${j}`;input.setAttribute('aria-label',`${j?'Im':'Re'} a${i}`);input.oninput=()=>{draftRoots[i][j]=Number(input.value);drawRoots();changed();};row.append(input);}host.append(row);}drawRoots();}
function drawRoots(){const c=$('rootsPlot'),k=c.getContext('2d'),w=c.width,h=c.height,scale=75,cx=w/2,cy=h/2;k.fillStyle='#fffef9';k.fillRect(0,0,w,h);k.strokeStyle='#dce3d8';k.beginPath();k.moveTo(0,cy);k.lineTo(w,cy);k.moveTo(cx,0);k.lineTo(cx,h);k.stroke();
 for(let i=2;i<5;i++){k.strokeStyle='#d4dfcf';k.strokeRect(cx+(reference[i][0]-.18)*scale,cy-(reference[i][1]+.18)*scale,.36*scale,.36*scale);}
 draftRoots.forEach((p,i)=>{if(!p.every(Number.isFinite))return;const x=cx+p[0]*scale,y=cy-p[1]*scale;k.fillStyle=i<2?'#6b7b72':['#d98343','#548cad','#a16eaa'][i-2];k.beginPath();k.arc(x,y,i<2?4:6,0,Math.PI*2);k.fill();k.font='11px system-ui';k.fillText(`a${i}`,x+7,y-7);});k.fillStyle='#667';k.fillText('a∞ fixed at infinity',8,16);
}
function updateBasis(){const spin=$('spin').value;if(spin==='odd_inf')$('basis').textContent='s²=dx/y; t=(A+Bx)s³.';else if(spin.startsWith('odd_'))$('basis').textContent='f=x−a; s²=f dx/y; t=(A+B/f)s³.';else $('basis').textContent='f=∏ of the three selected factors; s²=f dx/y; t=(A/f+B y/f²)s³. Regular chart formulas remove apparent poles.';}
function readSettings(){const inputs=['ar','ai','br','bi',...Array.from({length:3},(_,i)=>[`root${i+2}_0`,`root${i+2}_1`]).flat()];for(const id of inputs)if(!$(id).checkValidity()||!Number.isFinite(+$(id).value))throw Error('Check the numeric fields and branch-coordinate bounds.');return {roots:draftRoots.map(p=>[...p]),spin:$('spin').value,A:[+$('ar').value,+$('ai').value],B:[+$('br').value,+$('bi').value],level:+$('level').value};}
function fillSettings(s){draftRoots=s.roots.map(p=>[...p]);$('spin').value=s.spin;$('ar').value=s.A[0];$('ai').value=s.A[1];$('br').value=s.B[0];$('bi').value=s.B[1];$('level').value=s.level;rootControls();updateBasis();}
async function apply(){let settings;try{settings=readSettings();}catch(e){$('computeStatus').textContent=e.message;return;}const version=++jobVersion;$('apply').disabled=true;$('computeStatus').textContent='Submitting computation…';try{const job=await api('api/recompute',settings);if(version!==jobVersion)return;jobId=job.id;$('cancel').hidden=false;
 const poll=async()=>{if(version!==jobVersion)return;try{const status=await api(`api/jobs/${job.id}`);if(version!==jobVersion)return;$('computeStatus').textContent=status.message;if(status.status==='complete'){jobId=null;$('cancel').hidden=true;$('apply').disabled=false;$('computeStatus').classList.remove('dirty');await loadInfo();await generate();if(JSON.stringify(readSettings())!==JSON.stringify(settings))changed();}
 else if(['failed','cancelled'].includes(status.status)){jobId=null;$('cancel').hidden=true;$('apply').disabled=false;}
 else setTimeout(poll,1000);}catch(e){jobId=null;$('computeStatus').textContent=e.message;$('apply').disabled=false;$('cancel').hidden=true;}};poll();
 }catch(e){$('computeStatus').textContent=e.message;$('apply').disabled=false;}}
$('apply').onclick=apply;$('cancel').onclick=async()=>{if(jobId){await api(`api/cancel/${jobId}`,{});$('computeStatus').textContent='Cancelling…';}};
$('defaults').onclick=()=>{fillSettings({roots:reference,spin:'odd_inf',A:[.2,0],B:[0,0],level:7});changed();};
for(const id of ['spin','ar','ai','br','bi','level'])$(id).addEventListener('input',changed);
const rootsCanvas=$('rootsPlot');function rootPosition(e){const rect=rootsCanvas.getBoundingClientRect();return [(e.clientX-rect.left)*rootsCanvas.width/rect.width,(e.clientY-rect.top)*rootsCanvas.height/rect.height];}
rootsCanvas.onpointerdown=e=>{const [x,y]=rootPosition(e);rootDrag=[2,3,4].find(i=>Math.hypot(x-(130+75*draftRoots[i][0]),y-(115-75*draftRoots[i][1]))<15);if(rootDrag!==undefined)rootsCanvas.setPointerCapture(e.pointerId);};
rootsCanvas.onpointermove=e=>{if(rootDrag===null||rootDrag===undefined)return;const [x,y]=rootPosition(e),v=[(x-130)/75,(115-y)/75];draftRoots[rootDrag]=v.map((a,j)=>Math.round(Math.max(reference[rootDrag][j]-.18,Math.min(reference[rootDrag][j]+.18,a))*1000)/1000);for(let j=0;j<2;j++)$(`root${rootDrag}_${j}`).value=draftRoots[rootDrag][j];drawRoots();changed();};rootsCanvas.onpointerup=rootsCanvas.onpointercancel=()=>{rootDrag=null;};
function reset(){zoom=2;pan=[0,0];$('yaw').value=$('pitch').value=0;$('yawValue').textContent=$('pitchValue').textContent='0°';draw();}
$('sample').onclick=generate;$('reset').onclick=reset;$('mode').onchange=()=>{$('lengthLabel').textContent=$('mode').value==='words'?'Maximum word length':'Maximum conjugator length';};
for(const id of ['view','yaw','pitch','size'])$(id).addEventListener('input',()=>{if(id==='view'){zoom=2;pan=[0,0];}if(id==='yaw'||id==='pitch')$(id+'Value').textContent=$(id).value+'°';draw();});
canvas.addEventListener('wheel',e=>{if($('view').value==='sphere')return;e.preventDefault();zoom=Math.max(.01,Math.min(10000,zoom*Math.exp(e.deltaY*.001)));draw();},{passive:false});
canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY,...pan,+$('yaw').value,+$('pitch').value];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;if($('view').value==='sphere'){$('yaw').value=((drag[4]+(e.clientX-drag[0])*.4+540)%360)-180;$('pitch').value=Math.max(-90,Math.min(90,drag[5]-(e.clientY-drag[1])*.4));$('yawValue').textContent=$('yaw').value+'°';$('pitchValue').textContent=$('pitch').value+'°';}else{const r=Math.min(width,height)*.43;pan=[drag[2]-(e.clientX-drag[0])*zoom/r,drag[3]+(e.clientY-drag[1])*zoom/r];}draw();};canvas.onpointerup=canvas.onpointercancel=()=>{drag=null;};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('json').onclick=()=>{const data={...result,sphere_lifts:SphereView.lifts(result.points)};download(new Blob([JSON.stringify(data)],{type:'application/json'}),'barbot-limit-map-and-sphere-lifts.json');};$('png').onclick=()=>canvas.toBlob(blob=>download(blob,'barbot-sphere-limit-map.png'));
$('matrices').onclick=async()=>{try{download(new Blob([JSON.stringify(await api('api/holonomy'),null,2)],{type:'application/json'}),'barbot-holonomies.json');}catch(e){$('status').textContent=e.message;}};
new ResizeObserver(draw).observe(canvas.parentElement);rootControls();loadInfo(true).then(generate).catch(e=>{$('representation').textContent=e.message;});
